### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by fgalliat** [Legimet/duktape-nspire#1]
Hello,

I try to compile ducktape with Ndless SDK v3.6-r53.464a532 in order to continue your work on the Texture API, but I've got two errors : 
- -std=gnu11 unknwon argument (I replaced by -nostdlib)
-  error: #error "<dirent.h> not supported" because it seems to be no ?more? supported when it compile fs.c

I certainly made something wrong ... ;) I'll temporary try to descativate FS section and continue my work to make a pull request,

thanks in advance

**Comment by Legimet** [comment]
You need an up-to-date SDK. The SDK binaries available on unsads.com are 
outdated (unfortunately), so you will need to build it from source. I will 
refer you to [Hackspire](http://hackspire.unsads.com/wiki/index.php/C_and_assembly_development_introduction), 
which will tell you how to do that. On Windows or Mac OS X, things might not 
work perfectly. If you have any trouble building the SDK, feel free to ask on 
[CodeWalrus](https://codewalr.us/) or [TI-Planet](https://tiplanet.org/).

**Comment by adriweb** [comment]
Well, on OS X, I believe all I had to change in the SDK's `build_toolchain.sh` was to remove the Python option for GDB and to add `CXXFLAGS="-fbracket-depth=512"` to the GCC compile options :)

**Comment by fgalliat** [comment]
OK thanks

**Comment by Legimet** [comment]
Yeah, and I think on Windows it works using Cygwin, except for GDB.

**Comment by fgalliat** [comment]
thanks for all your advices, toolchain compilled (Cygwin on Win 10),
duktape recompilled as original Yeah !

I'm starting to port GFX routines to your code : already drawLines, drawRect, fillRect ...
polygons and circles are coming... hope I have no trouble to continue...

If you are interested, let me know

**Comment by Legimet** [comment]
Yes, I am very interested in seeing what you have :)

**Comment by fgalliat** [comment]
Sorry for another Noob Question, but
How do I push to GitHub (never did it before)

Username for 'https://github.com':
Password for 'https://fgalliat@github.com':
remote: Permission to Legimet/duktape-nspire.git denied to fgalliat.
fatal: unable to access 'https://github.com/Legimet/duktape-nspire.git/': The requested URL returned error: 403

![fb](https://cloud.githubusercontent.com/assets/3747118/9986943/865fdcd6-6042-11e5-95bb-bb5b2c12d967.png)

**Comment by fgalliat** [comment]
I think I found for pull request... let me know...
