### ISSUE TITLE
No way to quit?

### ISSUE THREAD

**Issue by flagstone78** [Legimet/duktape-nspire#3]
I just got a ti nspire cx cas. I put this on becasue I mostly program in javascript. I cant seem to find a way out of the console. Is there a user guide anywhere?

**Comment by flagstone78** [comment]
I found the way to quit is to enter ".quit". This would be useful to put on the readme page.

**Comment by Legimet** [comment]
OK that was an oversight. It is ".exit" and I will add it to the readme.
